services:

    request_data.extractor:
        class: 'Bilyiv\RequestDataBundle\Extractor\Extractor'
        arguments: ['@request_stack']

    request_data.type_converter:
        class: 'Bilyiv\RequestDataBundle\TypeConverter\TypeConverter'

    request_data.normalizer.request_data:
        class: 'Bilyiv\RequestDataBundle\Normalizer\RequestDataNormalizer'
        arguments: ['@request_stack', '@serializer.normalizer.object', '@request_data.type_converter', '']
        tags:
            - {name: 'serializer.normalizer'}

    request_data.controller_listener:
        class: 'Bilyiv\RequestDataBundle\EventListener\ControllerListener'
        arguments: ['@serializer', '@validator', '@request_data.extractor']
        tags:
            - {name: 'kernel.event_listener', event: 'kernel.controller'}